name: auth0_guardian_ios
description: "iOS implementation of the auth0_guardian plugin."
version: 0.1.1
repository: https://github.com/Kpler/auth0-guardian-flutter/tree/main/auth0_guardian_ios
issue_tracker: https://github.com/Kpler/auth0-guardian-flutter/issues
topics: 
  - auth0
  - guardian
  - multi-factor-authentication

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  auth0_guardian_platform_interface: ^0.1.1
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    implements: auth0_guardian
    platforms:
      ios:
        pluginClass: Auth0GuardianFlutterPlugin
        dartPluginClass: IosAuth0GuardianPlatform
        

