name: auth0_guardian
description: "A Flutter plugin that wraps the Auth0 Guardian SDKs and allow an easy implementation of multi-factor authentication."
version: 0.1.1
repository: https://github.com/Kpler/auth0-guardian-flutter/tree/main/auth0_guardian
issue_tracker: https://github.com/Kpler/auth0-guardian-flutter/issues
topics: 
  - auth0
  - guardian
  - multi-factor-authentication

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  auth0_guardian_platform_interface: ^0.1.1
  # auth0_guardian_android: ^0.1.1
  auth0_guardian_ios: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        default_package: auth0_guardian_android
      ios:
        default_package: auth0_guardian_ios